version: '3.7'
services:

  movie-search-sync:
    build:
      context: .
      target: builder
    depends_on:
      - movie-search-api
    command: npm run sync

  movie-search-api:
    build: .
    depends_on:
      - mailisearch
    ports:
      - 3000:3000

  mailisearch:
    image: getmeili/meilisearch:v0.27.1
    ports:
      - 7700:7700
    volumes:
      - ./.docker/meili_data:/meili_data
